# Generated by Django 4.2.7 on 2023-11-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='food_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('calories', models.IntegerField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='diet_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.clients')),
                ('food_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.food_table')),
            ],
        ),
        migrations.CreateModel(
            name='clients_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('gender', models.BooleanField()),
                ('phone_number', models.CharField(max_length=30)),
                ('Note', models.CharField(max_length=256)),
                ('clients_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.clients')),
            ],
        ),
    ]
