# Generated by Django 4.2.7 on 2023-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_table',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
